import { useEffect, useState } from 'react';
import { Check, Globe2, LockKeyhole, Plus, RefreshCw, ScanLine, ShieldAlert, ShieldCheck } from 'lucide-react';
import { api, post } from './api';
import type { Asset } from './types';

type ScanRow={id:string;asset_id:string;status:string;progress:number;error?:string;created_at:string};
export default function AssetsPage({en}:{en:boolean}){
 const [assets,setAssets]=useState<Asset[]>([]),[scans,setScans]=useState<ScanRow[]>([]),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({name:'',type:'DOMAIN',hostname:'',environment:'PRODUCTION',owner:''});
 async function load(){try{const [a,s]=await Promise.all([api<Asset[]>('/assets'),api<ScanRow[]>('/scans')]);setAssets(a);setScans(s)}catch(e){setError(e instanceof Error?e.message:'Load failed')}}
 useEffect(()=>{load()},[]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await post('/assets',form);setForm({name:'',type:'DOMAIN',hostname:'',environment:'PRODUCTION',owner:''});setShow(false);await load()}catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setBusy(false)}}
 async function authorize(a:Asset){const statement=window.prompt(en?`Confirm your authority to test ${a.hostname}. Describe the permission basis:`:`أكد صلاحيتك لفحص ${a.hostname}. اذكر أساس التفويض:`);if(!statement||statement.trim().length<30){setError(en?'A written authorization statement of at least 30 characters is required.':'يلزم إدخال بيان تفويض مكتوب لا يقل عن 30 حرفاً.');return}try{await post(`/assets/${a.id}/authorize`,{confirmed:true,statement});await load()}catch(e){setError(e instanceof Error?e.message:'Authorization failed')}}
 async function scan(a:Asset){setError('');try{await post(`/assets/${a.id}/scans`);await load()}catch(e){setError(e instanceof Error?e.message:'Scan could not be queued')}}
 const t=en?{title:'Authorized assets',desc:'Only assets with recorded authorization can be assessed.',add:'Add asset',name:'Asset name',host:'Hostname (no URL path)',type:'Type',owner:'Owner / team',save:'Save asset',cancel:'Cancel',empty:'No assets yet. Add an asset, then record explicit authorization before scanning.',authorize:'Record authorization',scan:'Start safe check',authorized:'Authorized',pending:'Pending',revoked:'Revoked',scans:'Recent assessments',noScans:'No scans have been started.',environment:'Environment'}:{title:'الأصول المصرح بها',desc:'لا يمكن تقييم الأصل إلا بعد تسجيل تفويض صريح.',add:'إضافة أصل',name:'اسم الأصل',host:'اسم المضيف (دون مسار URL)',type:'النوع',owner:'المالك / الفريق',save:'حفظ الأصل',cancel:'إلغاء',empty:'لا توجد أصول بعد. أضف أصلاً ثم سجّل التفويض صراحة قبل الفحص.',authorize:'تسجيل التفويض',scan:'بدء الفحص الآمن',authorized:'مصرّح',pending:'بانتظار التفويض',revoked:'ملغى',scans:'الفحوص الأخيرة',noScans:'لم يبدأ أي فحص بعد.',environment:'البيئة'};
 return <div className="page-content"><header className="page-heading"><div><div className="eyebrow">{en?'INVENTORY & AUTHORIZATION':'الجرد والتفويض'}</div><h1>{t.title}</h1><p>{t.desc}</p></div><button className="primary-btn" onClick={()=>setShow(!show)}><Plus size={16}/>{t.add}</button></header>{error&&<div className="form-error page-error">{error}</div>}
 {show&&<form className="form-panel asset-form" onSubmit={create}><label>{t.name}<input required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>{t.host}<input required placeholder="example.com" value={form.hostname} onChange={e=>setForm({...form,hostname:e.target.value})}/></label><label>{t.type}<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{['DOMAIN','SUBDOMAIN','WEBSITE','SERVER','APPLICATION','API','ENDPOINT','IP'].map(v=><option key={v}>{v}</option>)}</select></label><label>{t.owner}<input value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/></label><label>{t.environment}<select value={form.environment} onChange={e=>setForm({...form,environment:e.target.value})}><option>PRODUCTION</option><option>STAGING</option><option>DEVELOPMENT</option></select></label><div className="form-actions"><button className="primary-btn" disabled={busy}>{t.save}</button><button type="button" className="secondary-btn" onClick={()=>setShow(false)}>{t.cancel}</button></div></form>}
 <section className="asset-grid">{assets.length?assets.map(a=><article className="asset-card" key={a.id}><div className="asset-card-top"><div className="asset-type-icon"><Globe2 size={20}/></div><span className={`status-chip ${a.authorization_status==='AUTHORIZED'?'ok':a.authorization_status==='REVOKED'?'muted-chip':'warn'}`}>{a.authorization_status==='AUTHORIZED'?<ShieldCheck size={13}/>:<LockKeyhole size={13}/>} {t[a.authorization_status==='AUTHORIZED'?'authorized':a.authorization_status==='REVOKED'?'revoked':'pending']}</span></div><h3>{a.name}</h3><div className="host-line">{a.hostname}</div><div className="asset-meta"><span>{a.type}</span><span>{a.environment}</span></div><div className="asset-card-foot">{a.authorization_status!=='AUTHORIZED'?<button className="secondary-btn compact" onClick={()=>authorize(a)}><Check size={14}/>{t.authorize}</button>:<button className="primary-btn compact" onClick={()=>scan(a)}><ScanLine size={14}/>{t.scan}</button>}<span className="asset-owner">{a.owner||'—'}</span></div>{a.last_checked_at&&<div className="last-scan">{en?'Last checked':'آخر تحقق'} · {new Date(a.last_checked_at).toLocaleString(en?'en':'ar')}</div>}</article>):<div className="empty-state wide"><Globe2 size={32}/><p>{t.empty}</p></div>}</section>
 <section className="table-card"><div className="section-head"><div><h3>{t.scans}</h3><p>{en?'Background task status from the database':'حالة المهام الخلفية من قاعدة البيانات'}</p></div><button className="icon-button" onClick={load} aria-label="Refresh"><RefreshCw size={15}/></button></div>{scans.length?<div className="scan-list">{scans.slice(0,10).map(s=><div className="scan-row" key={s.id}><ScanLine size={16}/><span className="scan-host">{assets.find(a=>a.id===s.asset_id)?.hostname||s.asset_id.slice(0,8)}</span><span className={`status-chip ${s.status==='COMPLETED'?'ok':s.status==='FAILED'?'danger':'warn'}`}>{s.status}</span><span className="progress-track"><i style={{width:`${s.progress}%`}}/></span><time>{new Date(s.created_at).toLocaleString(en?'en':'ar')}</time>{s.error&&<small className="error-text">{s.error}</small>}</div>)}</div>:<div className="empty-inline"><ShieldAlert size={16}/>{t.noScans}</div>}</section>
 </div>
}
