import { useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import { post } from './api';
import type { Session } from './types';

export default function AuthPage({ onAuth, en }: { onAuth: (s: Session) => void; en: boolean }) {
  const [register, setRegister] = useState(false);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ full_name: '', email: '', password: '', organization_name: '' });
  const text = en ? { login: 'Sign in', create: 'Create account', name: 'Full name', email: 'Work email', pass: 'Password (12+ characters)', org: 'Organization name', submit: register ? 'Create secure workspace' : 'Sign in securely', switch: register ? 'Already have an account? Sign in' : 'New to CyberShield? Create an account', note: 'Security starts with the assets you are authorized to assess.' } : { login: 'تسجيل الدخول', create: 'إنشاء حساب', name: 'الاسم الكامل', email: 'البريد الإلكتروني للعمل', pass: 'كلمة المرور (12 حرفاً فأكثر)', org: 'اسم المؤسسة', submit: register ? 'إنشاء مساحة عمل آمنة' : 'تسجيل الدخول بأمان', switch: register ? 'لديك حساب؟ سجّل الدخول' : 'جديد في CyberShield؟ أنشئ حساباً', note: 'الأمن يبدأ بالأصول التي تملك تفويضاً لفحصها.' };
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const result = register ? await post<Session & { organization: { id: string; name: string } }>('/auth/register', form) : await post<Session>('/auth/login', { email: form.email, password: form.password }); onAuth(result); } catch (e) { setError(e instanceof Error ? e.message : 'Request failed'); } finally { setBusy(false); } }
  return <main className="auth-shell"><div className="auth-art"><div className="brand-mark large"><ShieldCheck size={36}/></div><span className="eyebrow">CYBERSHIELD OS · SECURITY OPERATIONS</span><h1>{en ? 'Clarity for your security posture.' : 'رؤية أوضح لوضعك الأمني.'}</h1><p>{text.note}</p><div className="auth-orbit"><div/><span>ASSET → ASSESS → REMEDIATE</span></div></div><form className="auth-card" onSubmit={submit}><div className="brand-lockup"><span className="brand-mark"><ShieldCheck size={21}/></span><b>CyberShield <em>OS</em></b></div><h2>{register ? text.create : text.login}</h2><p className="muted">{en ? 'Use your organization account to continue.' : 'استخدم حساب مؤسستك للمتابعة.'}</p>{register && <label>{text.name}<input autoComplete="name" required minLength={2} value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label>}<label>{text.email}<input type="email" autoComplete="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>{text.pass}<input type="password" autoComplete={register?'new-password':'current-password'} minLength={register?12:1} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{register && <label>{text.org}<input required minLength={2} value={form.organization_name} onChange={e=>setForm({...form,organization_name:e.target.value})}/></label>}{error && <div className="form-error">{error}</div>}<button className="primary-btn full" disabled={busy}>{busy ? '…' : text.submit}</button><button type="button" className="link-btn" onClick={()=>{setRegister(!register);setError('')}}>{text.switch}</button><div className="auth-security"><span className="pulse-dot"/> {en ? 'Encrypted session · Organization-isolated data' : 'جلسة مشفرة · بيانات معزولة لكل مؤسسة'}</div></form></main>
}
