import { useEffect, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, ArrowDownLeft, ArrowUpLeft, Box, CircleAlert, Fingerprint, ShieldAlert, ShieldCheck, Siren } from 'lucide-react';
import { api } from './api';
import type { DashboardData } from './types';

const colors = ['#fa6574','#ffab60','#f3cf6c','#6ec7aa','#7896f4'];
export default function DashboardPage({ en }: { en: boolean }) {
 const [data,setData]=useState<DashboardData|null>(null); const [error,setError]=useState('');
 useEffect(()=>{api<DashboardData>('/dashboard').then(setData).catch(e=>setError(e.message))},[]);
 if(error)return <div className="error-panel">{error}</div>; if(!data)return <div className="loading">{en?'Loading organization data…':'جارٍ تحميل بيانات المؤسسة…'}</div>;
 const label = (en?data.risk_level:({Excellent:'ممتاز',Good:'جيد','Needs Attention':'يحتاج إلى متابعة','High Risk':'مخاطر مرتفعة','Critical Risk':'خطر حرج'} as Record<string,string>)[data.risk_level]||data.risk_level);
 const severity = [{name:en?'Critical':'حرج',value:data.severity_distribution.CRITICAL||0},{name:en?'High':'مرتفع',value:data.severity_distribution.HIGH||0},{name:en?'Medium':'متوسط',value:data.severity_distribution.MEDIUM||0},{name:en?'Low':'منخفض',value:data.severity_distribution.LOW||0},{name:en?'Info':'معلومات',value:data.severity_distribution.INFO||0}];
 const statCards=[{label:en?'Critical findings':'نتائج حرجة',value:data.critical_findings,icon:CircleAlert,color:'red'},{label:en?'High findings':'نتائج مرتفعة',value:data.high_findings,icon:ShieldAlert,color:'orange'},{label:en?'Assets':'الأصول',value:data.assets,icon:Box,color:'blue'},{label:en?'Vulnerable assets':'أصول متأثرة',value:data.vulnerable_assets,icon:Fingerprint,color:'purple'},{label:en?'Open incidents':'حوادث مفتوحة',value:data.open_incidents,icon:Siren,color:'red'},{label:en?'Open risks':'مخاطر مفتوحة',value:data.open_risks,icon:Activity,color:'amber'}];
 return <div className="page-content"><header className="page-heading"><div><div className="eyebrow">{en?'SECURITY POSTURE':'الوضع الأمني'}</div><h1>{en?'Security overview':'نظرة عامة على الأمن'}</h1><p>{en?'Evidence-led view of your organization’s authorized assets.':'رؤية مبنية على الأدلة لأصول مؤسستك المصرح بها.'}</p></div><span className="live-pill"><i/> {en?'Live data':'بيانات مباشرة'}</span></header>
 <section className="overview-row"><article className="score-card"><div className="score-card-head"><span>{en?'Security score':'درجة الأمان'}</span><ShieldCheck size={18}/></div><div className="score-wrap"><div className="score-gauge" style={{'--score':`${data.security_score*3.6}deg`} as React.CSSProperties}><div><b>{data.security_score}</b><small>/100</small></div></div><div><b className="score-state">{label}</b><span className="muted small-block">{en?'Calculated from saved findings, risks, incidents and asset authorization.':'محسوبة من النتائج والمخاطر والحوادث وتفويض الأصول المحفوظة.'}</span></div></div><div className="score-foot"><span>{en?'Organization score':'درجة المؤسسة'}</span><span>{data.score_history.length} {en?'recorded points':'قراءة محفوظة'}</span></div></article>
 <article className="chart-card trend-card"><div className="section-head"><div><h3>{en?'Score trend':'اتجاه الدرجة'}</h3><p>{en?'Stored score snapshots':'لقطات الدرجة المسجلة'}</p></div><span className="chart-icon"><Activity size={17}/></span></div><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.score_history}><defs><linearGradient id="scoreFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4fc9ad" stopOpacity={.3}/><stop offset="95%" stopColor="#4fc9ad" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 4" stroke="#203442" vertical={false}/><XAxis dataKey="date" tickFormatter={v=>new Date(v).toLocaleDateString(en?'en':'ar',{month:'short',day:'numeric'})} tick={{fill:'#8194a0',fontSize:10}} axisLine={false} tickLine={false}/><YAxis domain={[0,100]} width={28} tick={{fill:'#8194a0',fontSize:10}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#12232e',border:'1px solid #294150',borderRadius:10}}/><Area type="monotone" dataKey="score" stroke="#4fc9ad" strokeWidth={2.5} fill="url(#scoreFill)"/></AreaChart></ResponsiveContainer></div></article>
 <article className="chart-card severity-card"><div className="section-head"><div><h3>{en?'Findings by severity':'النتائج حسب الشدة'}</h3><p>{en?'Unresolved records':'السجلات غير المعالجة'}</p></div><span className="chart-icon"><ShieldAlert size={17}/></span></div><div className="severity-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={severity} dataKey="value" nameKey="name" innerRadius={47} outerRadius={67} paddingAngle={3} stroke="none">{severity.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip contentStyle={{background:'#12232e',border:'1px solid #294150',borderRadius:10}}/></PieChart></ResponsiveContainer><div className="chart-center"><b>{severity.reduce((a,x)=>a+x.value,0)}</b><small>{en?'open':'مفتوح'}</small></div></div><div className="severity-legend">{severity.slice(0,4).map((x,i)=><span key={x.name}><i style={{background:colors[i]}}/>{x.name}<b>{x.value}</b></span>)}</div></article></section>
 <section className="stats-grid">{statCards.map(({label,value,icon:Icon,color})=><article className="stat-card" key={label}><div className={`stat-icon ${color}`}><Icon size={17}/></div><div><span>{label}</span><b>{value}</b></div><ArrowDownLeft size={14} className="stat-arrow"/></article>)}</section>
 <section className="lower-grid"><article className="chart-card category-card"><div className="section-head"><div><h3>{en?'Findings by category':'النتائج حسب الفئة'}</h3><p>{en?'Based on stored open findings':'وفق النتائج المفتوحة المسجلة'}</p></div></div>{data.findings_by_category.length?<div className="bar-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.findings_by_category} layout="vertical" margin={{left:12,right:20}}><CartesianGrid strokeDasharray="3 4" stroke="#203442" horizontal={false}/><XAxis type="number" allowDecimals={false} tick={{fill:'#8194a0',fontSize:10}} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="category" width={120} tick={{fill:'#a8b6bf',fontSize:11}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#12232e',border:'1px solid #294150',borderRadius:10}}/><Bar dataKey="count" fill="#5fc5ad" radius={[0,5,5,0]} barSize={13}/></BarChart></ResponsiveContainer></div>:<div className="empty-state"><ShieldCheck size={28}/><p>{en?'No open findings yet.':'لا توجد نتائج مفتوحة حتى الآن.'}</p></div>}</article>
 <article className="chart-card exposure-card"><div className="section-head"><div><h3>{en?'Asset exposure':'انكشاف الأصول'}</h3><p>{en?'Authorization and active findings':'التفويض والنتائج النشطة'}</p></div></div>{data.asset_exposure.length?<div className="exposure-list">{data.asset_exposure.slice(0,6).map(a=><div className="exposure-row" key={a.name}><span className="exposure-mark"><Box size={15}/></span><div className="exposure-name"><b>{a.name}</b><small>{a.authorized?(en?'Authorized':'مصرّح'):(en?'Pending authorization':'بانتظار التفويض')}</small></div><span className={`exposure-count ${a.findings?'is-risk':''}`}>{a.findings} {en?'findings':'نتائج'}</span></div>)}</div>:<div className="empty-state"><Box size={27}/><p>{en?'Add an asset to begin.':'أضف أصلاً لبدء المتابعة.'}</p></div>}</article></section>
 <div className="data-note"><ShieldCheck size={14}/>{en?'Metrics reflect this organization’s persisted records. Missing modules are not estimated.':'المؤشرات مبنية على سجلات المؤسسة المحفوظة؛ لا تُقدّر بيانات الوحدات غير المفعّلة.'}</div></div>
}
