import { useEffect, useState } from 'react';
import { KeyRound, Laptop, ShieldCheck, X } from 'lucide-react';
import { api, post } from './api';
import type { Session } from './types';
type Row={id:string;current:boolean;ip_address?:string;user_agent?:string;created_at:string;expires_at:string};
export default function SettingsPage({en,session}:{en:boolean;session:Session}){
 const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[current,setCurrent]=useState(''),[next,setNext]=useState('');
 async function load(){try{setRows(await api<Row[]>('/auth/sessions'))}catch(e){setError(e instanceof Error?e.message:'Could not load sessions')}}
 useEffect(()=>{load()},[]);
 async function revoke(id:string){setError('');try{await api(`/auth/sessions/${id}`,{method:'DELETE'});await load()}catch(e){setError(e instanceof Error?e.message:'Could not revoke session')}}
 async function change(e:React.FormEvent){e.preventDefault();setError('');setNotice('');try{const r=await post<{revoked_other_sessions:number}>('/auth/change-password',{current_password:current,new_password:next});setNotice(en?`Password changed. ${r.revoked_other_sessions} other session(s) revoked.`:`تم تغيير كلمة المرور وإبطال ${r.revoked_other_sessions} جلسة أخرى.`);setCurrent('');setNext('');await load()}catch(e){setError(e instanceof Error?e.message:'Could not change password')}}
 return <div className="page-content"><header className="page-heading"><div><div className="eyebrow">{en?'ACCOUNT SECURITY':'أمن الحساب'}</div><h1>{en?'Sessions & settings':'الجلسات والإعدادات'}</h1><p>{en?'Review devices, revoke sessions and rotate your password.':'راجع الأجهزة وأبطل الجلسات وغيّر كلمة المرور.'}</p></div></header><section className="settings-grid"><article className="settings-card"><span className="settings-icon"><KeyRound size={19}/></span><h3>{en?'Account':'الحساب'}</h3><p>{session.user.full_name}<br/><span className="muted">{session.user.email}</span></p><div className="settings-line"><span>{en?'Organization':'المؤسسة'}</span><b>{session.organization?.name||'—'}</b></div><div className="settings-line"><span>{en?'Role':'الدور'}</span><b>{session.role}</b></div><form className="password-form" onSubmit={change}><h4>{en?'Change password':'تغيير كلمة المرور'}</h4><input type="password" required minLength={1} autoComplete="current-password" placeholder={en?'Current password':'كلمة المرور الحالية'} value={current} onChange={e=>setCurrent(e.target.value)}/><input type="password" required minLength={12} autoComplete="new-password" placeholder={en?'New password (12+ characters)':'كلمة المرور الجديدة (12 حرفاً فأكثر)'} value={next} onChange={e=>setNext(e.target.value)}/><button className="secondary-btn">{en?'Update password':'تحديث كلمة المرور'}</button></form>{notice&&<div className="success-note">{notice}</div>}</article><article className="settings-card wide-settings"><div className="section-head"><div><span className="settings-icon"><Laptop size={19}/></span><h3>{en?'Active sessions':'الجلسات النشطة'}</h3><p>{en?'Sessions expire after eight hours. Revoke devices you do not recognize.':'تنتهي الجلسات بعد ثماني ساعات. أبطل أي جلسة لا تتعرف عليها.'}</p></div></div>{error&&<div className="form-error">{error}</div>}{rows.map(r=><div className="session-row" key={r.id}><span className="session-icon"><Laptop size={17}/></span><div><b>{r.current?(en?'Current session':'الجلسة الحالية'):(r.user_agent||'Browser session')}</b><small>{r.ip_address||'IP not recorded'} · {new Date(r.created_at).toLocaleString(en?'en':'ar')}</small></div><span className={`status-chip ${r.current?'ok':'muted-chip'}`}>{r.current?(en?'Active now':'نشطة الآن'):(en?'Active':'نشطة')}</span>{!r.current&&<button className="icon-button" onClick={()=>revoke(r.id)} title={en?'Revoke this session':'إبطال هذه الجلسة'}><X size={15}/></button>}</div>)}</article></section><div className="data-note"><ShieldCheck size={14}/>{en?'Passwords use Argon2id. Session cookies are HttpOnly; unsafe requests require CSRF validation.':'تُخزّن كلمات المرور بتجزئة Argon2id. ملف الجلسة HttpOnly والطلبات المعدّلة محمية برمز CSRF.'}</div></div>
}
