import { FormEvent, ReactNode, useCallback, useEffect, useState } from 'react';
import { Activity, AlertTriangle, ArrowUpRight, Bell, Check, CircleDot, Clock3, Database, Globe2, KeyRound, Plus, RefreshCw, ShieldAlert, Trash2, Wifi, WifiOff, X } from 'lucide-react';
import { api, patch, post } from './api';

type Props = { en: boolean };
type Row = Record<string, any>;
const words = (en: boolean, ar: string, english: string) => en ? english : ar;
const fmt = (value: unknown, en: boolean) => value ? new Date(String(value)).toLocaleString(en ? 'en-US' : 'ar', { dateStyle: 'medium', timeStyle: 'short' }) : '—';
const label = (value: string, en: boolean) => {
  const map: Record<string, [string,string]> = {
    CRITICAL:['حرج','Critical'], HIGH:['عالٍ','High'], MEDIUM:['متوسط','Medium'], LOW:['منخفض','Low'], INFO:['معلومات','Info'],
    NEW:['جديد','New'], ACKNOWLEDGED:['تم الإقرار','Acknowledged'], INVESTIGATING:['قيد التحقيق','Investigating'], RESOLVED:['محلول','Resolved'], FALSE_POSITIVE:['إيجابي كاذب','False positive'],
    OPEN:['مفتوح','Open'], CONTAINED:['تم الاحتواء','Contained'], CLOSED:['مغلق','Closed'], IN_PROGRESS:['قيد التنفيذ','In progress'], TODO:['للتنفيذ','To do'], DONE:['مكتمل','Done'],
    MEASURED:['مقاس','Measured'], INSUFFICIENT_DATA:['بيانات غير كافية','Insufficient data'], NOT_ASSESSED:['غير مُقيّم','Not assessed'],
  };
  return map[value]?.[en ? 1 : 0] ?? value?.replace(/_/g,' ') ?? '—';
};
function useMessage() {
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const run = async (fn: () => Promise<unknown>, ok = '') => {
    setError(''); setMessage('');
    try { await fn(); setMessage(ok); return true; }
    catch (e) { setError(e instanceof Error ? e.message : 'Request failed'); return false; }
  };
  return { message, error, setMessage, setError, run };
}
function Notice({ message, error, en }: {message:string;error:string;en:boolean}) {
  if (!message && !error) return null;
  return <div className={`soc-notice ${error?'is-error':''}`}>{error || message}</div>;
}
function Heading({en,title,description,action}:{en:boolean;title:string;description:string;action?:ReactNode}) {
  return <div className="page-heading"><div><span className="eyebrow">CYBERSHIELD / SOC</span><h1>{title}</h1><p>{description}</p></div>{action}</div>;
}
function Stat({icon:Icon,title,value,tone='teal',note}:{icon:any;title:string;value:React.ReactNode;tone?:string;note?:string}) {
  return <div className="soc-stat"><span className={`soc-stat-icon ${tone}`}><Icon size={17}/></span><div><small>{title}</small><b>{value}</b>{note&&<em>{note}</em>}</div></div>;
}

export function SocCenterPage({en}:Props) {
  const [overview,setOverview]=useState<Row|null>(null), [metrics,setMetrics]=useState<Row|null>(null), [events,setEvents]=useState<Row[]>([]), [connection,setConnection]=useState<'connecting'|'live'|'offline'>('connecting');
  const {error,setError}=useMessage();
  const refresh=useCallback(async()=>{try{const [o,m]=await Promise.all([api<Row>('/soc/overview'),api<Row>('/soc/metrics?period=24h')]);setOverview(o);setMetrics(m);setEvents(prev=>{const merged=[...(o.recent_events||[]),...prev];return Array.from(new Map(merged.map(x=>[x.id,x])).values()).slice(0,40)});setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load SOC data')}},[setError]);
  useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),30000);return()=>window.clearInterval(timer)},[refresh]);
  useEffect(()=>{let socket:WebSocket|undefined, retry:number|undefined, stopped=false;const connect=()=>{if(stopped)return;setConnection('connecting');const protocol=location.protocol==='https:'?'wss:':'ws:';socket=new WebSocket(`${protocol}//${location.host}/api/ws/events`);socket.onopen=()=>setConnection('live');socket.onmessage=(event)=>{try{const data=JSON.parse(event.data);if(data.type==='security_event'&&data.event){setEvents(prev=>[data.event,...prev].slice(0,40));void refresh()}else if(data.type==='notification'||data.type==='security_alert'){void refresh()}}catch{}};socket.onclose=()=>{setConnection('offline');if(!stopped)retry=window.setTimeout(connect,4000)};socket.onerror=()=>socket?.close()};connect();return()=>{stopped=true;if(retry)clearTimeout(retry);socket?.close()}},[refresh]);
  const cards=overview||{};
  const eventsList=events.length?events:(cards.recent_events||[]);
  const sev=metrics?.alerts_by_severity||{};
  return <div className="page-content"><Heading en={en} title={words(en,'مركز العمليات الأمنية','Security Operations Center')} description={words(en,'صورة لحظية للأحداث والتنبيهات ومؤشرات الاستجابة؛ القيم مشتقة من سجلات المؤسسة.','Live view of events, alerts and response metrics, derived from organization records.')} action={<span className={`live-pill ${connection==='live'?'':'offline'}`}><i/>{connection==='live'?words(en,'البث مباشر','Live stream'):words(en,'إعادة الاتصال','Reconnecting')}</span>}/>
    {error&&<div className="soc-inline-error">{error}<button onClick={()=>void refresh()}><RefreshCw size={14}/></button></div>}
    <div className="soc-stat-grid">
      <Stat icon={ShieldAlert} title={words(en,'الحالة العامة','Overall status')} value={label(cards.overall_status||'—',en)} tone={cards.overall_status==='ATTENTION'?'red':'teal'}/>
      <Stat icon={AlertTriangle} title={words(en,'الحوادث النشطة','Active incidents')} value={cards.active_incidents??'—'} tone="orange"/>
      <Stat icon={Bell} title={words(en,'التنبيهات الحرجة','Critical alerts')} value={cards.critical_alerts??'—'} tone="red"/>
      <Stat icon={Activity} title={words(en,'أحداث/دقيقة','Events/min')} value={cards.events_per_minute??'—'} tone="blue"/>
      <Stat icon={CircleDot} title={words(en,'نشاط التهديدات 24س','Threat activity · 24h')} value={cards.threat_activity_24h??'—'} tone="purple"/>
      <Stat icon={Database} title={words(en,'الأصول تحت المراقبة','Assets monitored')} value={cards.assets_under_monitoring??'—'} tone="teal"/>
      <Stat icon={Clock3} title="MTTD" value={cards.mttd_minutes==null?label(metrics?.mttd?.status||'INSUFFICIENT_DATA',en):`${cards.mttd_minutes} ${words(en,'دقيقة','min')}`} tone="blue" note={metrics?.mttd?.sample_count?`${metrics.mttd.sample_count} ${words(en,'عينات','samples')}`:undefined}/>
      <Stat icon={Clock3} title="MTTR" value={cards.mttr_minutes==null?label(metrics?.mttr?.status||'INSUFFICIENT_DATA',en):`${cards.mttr_minutes} ${words(en,'دقيقة','min')}`} tone="orange" note={metrics?.mttr?.sample_count?`${metrics.mttr.sample_count} ${words(en,'عينات','samples')}`:undefined}/>
    </div>
    <div className="soc-two-col">
      <section className="table-card soc-panel"><div className="section-head"><div><h3>{words(en,'تدفق الأحداث الأمنية','Live security event stream')}</h3><p>{words(en,'آخر الأحداث المعالجة أو الواردة','Most recent received or processed events')}</p></div><span className="socket-indicator">{connection==='live'?<Wifi size={15}/>:<WifiOff size={15}/>}</span></div>
        <div className="soc-event-list">{eventsList.length?eventsList.map((ev:Row)=><article className="soc-event" key={ev.id}><span className={`severity-rail ${String(ev.severity||'info').toLowerCase()}`}/><div className="soc-event-main"><div><b>{ev.event_type||ev.message||words(en,'حدث أمني','Security event')}</b><span className={`severity-label ${String(ev.severity||'info').toLowerCase()}`}>{label(ev.severity||'INFO',en)}</span></div><p>{ev.message||ev.source||'—'}</p><small>{ev.hostname||ev.source||'—'} · {fmt(ev.timestamp||ev.event_timestamp||ev.created_at,en)}</small></div></article>):<div className="empty-state"><Activity/><p>{words(en,'لا توجد أحداث بعد. اربط مصدراً عبر مفاتيح الإدخال لبدء التدفق.','No events yet. Configure an ingestion key to start the stream.')}</p></div>}</div>
      </section>
      <section className="table-card soc-panel"><div className="section-head"><div><h3>{words(en,'ملخص التنبيهات','Alert summary')}</h3><p>{words(en,'الأحداث والنتائج ضمن آخر 24 ساعة','Alerts and findings over the last 24 hours')}</p></div><a className="secondary-btn compact" href="#alerts">{words(en,'كل التنبيهات','All alerts')} <ArrowUpRight size={13}/></a></div>
        <div className="soc-severity-list">{[['CRITICAL','red'],['HIGH','orange'],['MEDIUM','yellow'],['LOW','teal'],['INFO','blue']].map(([s,t])=><div key={s}><span className={`severity-label ${s.toLowerCase()}`}>{label(s,en)}</span><i className="soc-bar"><b className={t} style={{width:`${Math.min(100,((sev[s]||0)/Math.max(1,...Object.values(sev).map(Number)))*100)}%`}}/></i><strong>{sev[s]||0}</strong></div>)}</div>
        <div className="soc-extra-stats"><div><small>{words(en,'التحقيقات المفتوحة','Open investigations')}</small><b>{cards.open_investigations??0}</b></div><div><small>{words(en,'قواعد الكشف المفعّلة','Detection rules')}</small><b>{cards.enabled_detection_rules??0}</b></div><div><small>{words(en,'قائمة معالجة الأحداث','Ingestion backlog')}</small><b>{cards.event_processing_backlog??0}</b></div></div>
        <p className="data-note">{words(en,'المقاييس بلا عينات حقيقية تظهر «بيانات غير كافية» بدلاً من قيمة تقديرية.','Metrics without real samples show insufficient data, never estimates.')}</p>
      </section>
    </div>
  </div>;
}

export function AlertsPage({en}:Props) {
  const [data,setData]=useState<Row>({items:[],total:0}), [q,setQ]=useState(''),[severity,setSeverity]=useState(''),[status,setStatus]=useState(''),[selected,setSelected]=useState<Row|null>(null),[note,setNote]=useState('');
  const {error,message,run}=useMessage();
  const load=useCallback(async()=>{const params=new URLSearchParams({limit:'100'});if(q)params.set('q',q);if(severity)params.set('severity',severity);if(status)params.set('status',status);setData(await api(`/alerts?${params}`))},[q,severity,status]);
  useEffect(()=>{void load().catch(()=>{})},[load]);
  async function open(row:Row){try{setSelected(await api(`/alerts/${row.id}`))}catch{setSelected(row)}}
  async function changeStatus(value:string){if(!selected)return;await run(async()=>{await patch(`/alerts/${selected.id}`,{status:value});await load();await open(selected)},words(en,'تم تحديث الحالة','Status updated'))}
  async function addNote(e:FormEvent){e.preventDefault();if(!selected||!note.trim())return;const text=note;const ok=await run(async()=>{await post(`/alerts/${selected.id}/notes`,{content:text});setNote('');await open(selected)},words(en,'أُضيفت الملاحظة','Note added'));if(ok)await load()}
  return <div className="page-content"><Heading en={en} title={words(en,'التنبيهات','Alerts')} description={words(en,'ابحث وصفّ وراجع دليل كل تنبيه وسجّل ملاحظات المحللين.','Filter alerts, review evidence and add analyst notes.')}/><Notice message={message} error={error} en={en}/>
    <div className="soc-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={words(en,'بحث في العنوان أو السبب أو المستخدم','Search title, reason or user')}/><select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">{words(en,'كل الشدّات','All severities')}</option>{['CRITICAL','HIGH','MEDIUM','LOW','INFO'].map(x=><option key={x} value={x}>{label(x,en)}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">{words(en,'كل الحالات','All statuses')}</option>{['NEW','ACKNOWLEDGED','INVESTIGATING','RESOLVED','FALSE_POSITIVE'].map(x=><option key={x}>{x}</option>)}</select><button className="secondary-btn compact" onClick={()=>void load()}><RefreshCw size={14}/>{words(en,'تحديث','Refresh')}</button></div>
    <div className="soc-workspace"><section className="table-card"><div className="section-head"><div><h3>{words(en,'قائمة التنبيهات','Alert queue')}</h3><p>{data.total||0} {words(en,'سجلاً ضمن المؤسسة','organization-scoped records')}</p></div></div><div className="soc-list">{(data.items||[]).map((row:Row)=><button key={row.id} className={`soc-list-row ${selected?.id===row.id?'selected':''}`} onClick={()=>void open(row)}><i className={`severity-rail ${String(row.severity).toLowerCase()}`}/><span><b>{row.title}</b><small>{row.reason||row.source||'—'}</small></span><span className={`status-chip ${row.severity==='CRITICAL'?'danger':row.severity==='HIGH'?'warn':'muted-chip'}`}>{label(row.severity,en)}</span><time>{fmt(row.created_at,en)}</time></button>)}{!data.items?.length&&<div className="empty-state"><Bell/><p>{words(en,'لا توجد تنبيهات مطابقة.','No matching alerts.')}</p></div>}</div></section>
      <section className="table-card soc-detail">{selected?<><div className="section-head"><div><span className={`severity-label ${String(selected.severity).toLowerCase()}`}>{label(selected.severity,en)}</span><h3>{selected.title}</h3></div><button className="secondary-btn compact" onClick={()=>setSelected(null)}><X size={14}/></button></div><p className="soc-description">{selected.description||selected.reason||'—'}</p><div className="soc-kv"><span>{words(en,'الحالة','Status')}</span><select value={selected.status} onChange={e=>void changeStatus(e.target.value)}>{['NEW','ACKNOWLEDGED','INVESTIGATING','RESOLVED','FALSE_POSITIVE'].map(x=><option key={x}>{x}</option>)}</select><span>{words(en,'المصدر','Source')}</span><b>{selected.source||'—'}</b><span>{words(en,'المضيف / الأصل','Host / asset')}</span><b>{selected.asset?.hostname||selected.hostname||'—'}</b><span>{words(en,'المستخدم','User')}</span><b>{selected.username||'—'}</b><span>{words(en,'درجة المخاطر','Risk score')}</span><b>{selected.risk_score??'—'}</b><span>{words(en,'القاعدة','Detection rule')}</span><b>{selected.detection_rule_id||'—'}</b></div>{selected.recommendation&&<><h4>{words(en,'إجراءات دفاعية مقترحة','Recommended defensive checks')}</h4><p className="soc-description">{selected.recommendation}</p></>}<h4>{words(en,'الأحداث المرتبطة','Related events')}</h4>{(selected.events||[]).map((x:Row)=><div className="soc-timeline" key={x.id}><i/><div><b>{x.event_type}</b><small>{x.message} · {fmt(x.timestamp,en)}</small></div></div>)}<h4>{words(en,'ملاحظات المحللين','Analyst notes')}</h4>{(selected.notes||[]).map((x:Row)=><div className="soc-note" key={x.id}>{x.content}<small>{fmt(x.created_at,en)}</small></div>)}<form className="soc-note-form" onSubmit={addNote}><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={words(en,'أضف ملاحظة مرتبطة بالأدلة…','Add an evidence-based note…')}/><button className="primary-btn compact" disabled={!note.trim()}><Plus size={14}/>{words(en,'إضافة ملاحظة','Add note')}</button></form></>:<div className="empty-state"><ShieldAlert/><p>{words(en,'اختر تنبيهاً لعرض السبب والأحداث المرتبطة.','Select an alert to inspect its rationale and related events.')}</p></div>}</section></div>
  </div>;
}

export function InvestigationsPage({en}:Props) {
  const [items,setItems]=useState<Row[]>([]),[members,setMembers]=useState<Row[]>([]),[selected,setSelected]=useState<Row|null>(null),[showForm,setShowForm]=useState(false),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[priority,setPriority]=useState('MEDIUM'),[assignee,setAssignee]=useState(''),[note,setNote]=useState(''),[task,setTask]=useState(''),[resourceType,setResourceType]=useState('ALERT'),[resourceId,setResourceId]=useState('');
  const {error,message,run}=useMessage();
  const load=useCallback(async()=>{const [i,m]=await Promise.all([api<Row[]>('/investigations'),api<Row[]>('/team/members')]);setItems(i);setMembers(m.filter(x=>x.status==='ACTIVE'))},[]);
  useEffect(()=>{void load().catch(()=>{})},[load]);
  async function open(row:Row){try{setSelected(await api(`/investigations/${row.id}`))}catch{setSelected(row)}}
  async function create(e:FormEvent){e.preventDefault();const ok=await run(async()=>{const row=await post<Row>('/investigations',{title,description,priority,assigned_to_id:assignee||null});setTitle('');setDescription('');setShowForm(false);await load();await open(row)},words(en,'أُنشئ التحقيق','Investigation created'));}
  async function saveStatus(value:string){if(!selected)return;await run(async()=>{await patch(`/investigations/${selected.id}`,{status:value});await load();await open(selected)},words(en,'تم تحديث التحقيق','Investigation updated'))}
  async function saveNote(e:FormEvent){e.preventDefault();if(!selected||!note.trim())return;const text=note;await run(async()=>{await post(`/investigations/${selected.id}/notes`,{note:text});setNote('');await open(selected)},words(en,'أُضيفت الملاحظة','Note added'))}
  async function createTask(e:FormEvent){e.preventDefault();if(!selected||!task.trim())return;const text=task;await run(async()=>{await post('/tasks',{title:text,investigation_id:selected.id,priority:'MEDIUM'});setTask('');await load();await open(selected)},words(en,'أُنشئت المهمة','Task created'))}
  async function linkResource(e:FormEvent){e.preventDefault();if(!selected||!resourceId.trim())return;const id=resourceId.trim();await run(async()=>{await post(`/investigations/${selected.id}/links`,{resource_type:resourceType,resource_id:id});setResourceId('');await open(selected)},words(en,'تم ربط المورد','Resource linked'))}
  return <div className="page-content"><Heading en={en} title={words(en,'مساحة التحقيقات','Investigation workspace')} description={words(en,'اربط التنبيهات والأحداث والأصول، وأسند المحللين وتابع الخط الزمني.','Link alerts, events and assets; assign analysts and review the timeline.')} action={<button className="primary-btn" onClick={()=>setShowForm(!showForm)}><Plus size={15}/>{words(en,'تحقيق جديد','New investigation')}</button>}/><Notice message={message} error={error} en={en}/>
    {showForm&&<form className="soc-create-form" onSubmit={create}><input required minLength={3} value={title} onChange={e=>setTitle(e.target.value)} placeholder={words(en,'عنوان التحقيق','Investigation title')}/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder={words(en,'وصف ونطاق التحقيق','Description and scope')}/><div className="soc-form-row"><select value={priority} onChange={e=>setPriority(e.target.value)}>{['LOW','MEDIUM','HIGH','CRITICAL'].map(x=><option key={x}>{x}</option>)}</select><select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">{words(en,'دون تعيين','Unassigned')}</option>{members.map(x=><option key={x.user_id} value={x.user_id}>{x.full_name}</option>)}</select><button className="primary-btn"><Check size={14}/>{words(en,'إنشاء','Create')}</button></div></form>}
    <div className="soc-workspace"><section className="table-card"><div className="section-head"><h3>{words(en,'التحقيقات','Investigations')}</h3><button className="secondary-btn compact" onClick={()=>void load()}><RefreshCw size={14}/></button></div><div className="soc-list">{items.map(row=><button key={row.id} className={`soc-list-row ${selected?.id===row.id?'selected':''}`} onClick={()=>void open(row)}><i className="severity-rail medium"/><span><b>{row.title}</b><small>{label(row.priority,en)} · {row.assigned_to_id?members.find(m=>m.user_id===row.assigned_to_id)?.full_name||'Assigned':'Unassigned'}</small></span><span className="status-chip muted-chip">{label(row.status,en)}</span></button>)}{!items.length&&<div className="empty-state"><Activity/><p>{words(en,'لا توجد تحقيقات بعد.','No investigations yet.')}</p></div>}</div></section>
    <section className="table-card soc-detail">{selected?<><div className="section-head"><div><span className="eyebrow">{selected.priority}</span><h3>{selected.title}</h3></div><select className="soc-status-select" value={selected.status} onChange={e=>void saveStatus(e.target.value)}>{['OPEN','INVESTIGATING','CONTAINED','RESOLVED','CLOSED'].map(x=><option key={x}>{x}</option>)}</select></div><p className="soc-description">{selected.description||words(en,'لا يوجد وصف.','No description.')}</p><div className="soc-detail-meta"><span>{words(en,'أُنشئ','Created')} {fmt(selected.created_at,en)}</span><span>{words(en,'المكلّف','Assignee')}: {members.find(m=>m.user_id===selected.assigned_to_id)?.full_name||'—'}</span></div><h4>{words(en,'الموارد المرتبطة','Linked resources')}</h4>{(selected.links||[]).map((x:Row)=><div className="soc-timeline" key={x.id}><i/><div><b>{x.resource_type}</b><small>{x.resource_id}</small></div></div>)}{!(selected.links||[]).length&&<small className="muted">{words(en,'لا توجد موارد مرتبطة.','No linked resources.')}</small>}<form className="soc-inline-form" onSubmit={linkResource}><select value={resourceType} onChange={e=>setResourceType(e.target.value)}>{['ALERT','EVENT','ASSET','FINDING','INCIDENT','CASE'].map(x=><option key={x}>{x}</option>)}</select><input value={resourceId} onChange={e=>setResourceId(e.target.value)} placeholder={words(en,'معرّف المورد','Resource ID')}/><button className="secondary-btn compact" disabled={!resourceId.trim()}><Plus size={14}/>{words(en,'ربط','Link')}</button></form><h4>{words(en,'المهام','Tasks')}</h4>{(selected.tasks||[]).map((x:Row)=><div className="soc-task" key={x.id}><span>{x.title}</span><select value={x.status} onChange={async e=>{await run(()=>patch(`/tasks/${x.id}`,{status:e.target.value}),words(en,'تم تحديث المهمة','Task updated'));await open(selected)}}>{['TODO','IN_PROGRESS','DONE'].map(s=><option key={s}>{s}</option>)}</select></div>)}<form className="soc-inline-form" onSubmit={createTask}><input value={task} onChange={e=>setTask(e.target.value)} placeholder={words(en,'مهمة متابعة جديدة','New follow-up task')}/><button className="secondary-btn compact" disabled={!task.trim()}><Plus size={14}/>{words(en,'مهمة','Task')}</button></form><h4>{words(en,'الخط الزمني','Timeline')}</h4>{(selected.timeline||[]).map((x:Row,i:number)=><div className="soc-timeline" key={`${x.resource_id}-${i}`}><i/><div><b>{x.label||x.type}</b><small>{fmt(x.at,en)}</small></div></div>)}<form className="soc-note-form" onSubmit={saveNote}><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={words(en,'ملاحظة تحليلية','Analyst note')}/><button className="primary-btn compact" disabled={!note.trim()}><Plus size={14}/>{words(en,'إضافة','Add')}</button></form></>:<div className="empty-state"><Activity/><p>{words(en,'اختر تحقيقاً من القائمة لعرض تفاصيله.','Select an investigation to view its workspace.')}</p></div>}</section></div>
  </div>;
}

export function CasesPage({en}:Props) {
  const [items,setItems]=useState<Row[]>([]),[selected,setSelected]=useState<Row|null>(null),[showForm,setShowForm]=useState(false),[title,setTitle]=useState(''),[priority,setPriority]=useState('MEDIUM'),[note,setNote]=useState(''),[resourceType,setResourceType]=useState('ALERT'),[resourceId,setResourceId]=useState(''); const {error,message,run}=useMessage();
  const load=useCallback(async()=>setItems(await api<Row[]>('/cases')),[]);useEffect(()=>{void load().catch(()=>{})},[load]);
  async function open(row:Row){try{setSelected(await api(`/cases/${row.id}`))}catch{setSelected(row)}}
  async function create(e:FormEvent){e.preventDefault();await run(async()=>{const row=await post<Row>('/cases',{title,priority});setTitle('');setShowForm(false);await load();await open(row)},words(en,'أُنشئت القضية','Case created'))}
  async function addNote(e:FormEvent){e.preventDefault();if(!selected||!note.trim())return;const text=note;await run(async()=>{await post(`/cases/${selected.id}/notes`,{note:text});setNote('');await open(selected)},words(en,'أُضيفت الملاحظة','Note added'))}
  async function linkResource(e:FormEvent){e.preventDefault();if(!selected||!resourceId.trim())return;const id=resourceId.trim();await run(async()=>{await post(`/cases/${selected.id}/links`,{resource_type:resourceType,resource_id:id});setResourceId('');await open(selected)},words(en,'تم ربط المورد بالقضية','Resource linked to case'))}
  return <div className="page-content"><Heading en={en} title={words(en,'إدارة القضايا','Case management')} description={words(en,'اجمع الحوادث والتنبيهات والموارد والملاحظات في سجل قضية واحد.','Bring incidents, alerts, resources and notes into one case record.')} action={<button className="primary-btn" onClick={()=>setShowForm(!showForm)}><Plus size={15}/>{words(en,'قضية جديدة','New case')}</button>}/><Notice message={message} error={error} en={en}/>{showForm&&<form className="soc-create-form soc-form-row" onSubmit={create}><input required minLength={3} value={title} onChange={e=>setTitle(e.target.value)} placeholder={words(en,'عنوان القضية','Case title')}/><select value={priority} onChange={e=>setPriority(e.target.value)}>{['LOW','MEDIUM','HIGH','CRITICAL'].map(x=><option key={x}>{x}</option>)}</select><button className="primary-btn"><Check size={14}/>{words(en,'إنشاء','Create')}</button></form>}
    <div className="soc-workspace"><section className="table-card"><div className="section-head"><h3>{words(en,'القضايا','Cases')}</h3><button className="secondary-btn compact" onClick={()=>void load()}><RefreshCw size={14}/></button></div><div className="soc-list">{items.map(row=><button key={row.id} className={`soc-list-row ${selected?.id===row.id?'selected':''}`} onClick={()=>void open(row)}><i className={`severity-rail ${String(row.priority).toLowerCase()}`}/><span><b>{row.case_number} · {row.title}</b><small>{label(row.priority,en)} · {fmt(row.created_at,en)}</small></span><span className="status-chip muted-chip">{label(row.status,en)}</span></button>)}{!items.length&&<div className="empty-state"><ClipboardIcon/><p>{words(en,'لا توجد قضايا بعد.','No cases yet.')}</p></div>}</div></section>
    <section className="table-card soc-detail">{selected?<><div className="section-head"><div><span className="eyebrow">{selected.case_number}</span><h3>{selected.title}</h3></div><select className="soc-status-select" value={selected.status} onChange={async e=>{await run(()=>patch(`/cases/${selected.id}`,{status:e.target.value}),words(en,'تم تحديث القضية','Case updated'));await load();await open(selected)}}>{['OPEN','IN_PROGRESS','RESOLVED','CLOSED'].map(x=><option key={x}>{x}</option>)}</select></div><h4>{words(en,'الروابط','Linked resources')}</h4>{(selected.links||[]).map((x:Row)=><div className="soc-timeline" key={x.id}><i/><div><b>{x.resource_type}</b><small>{x.resource_id} · {fmt(x.created_at,en)}</small></div></div>)}{!(selected.links||[]).length&&<div className="empty-inline">{words(en,'لا توجد موارد مرتبطة. يمكن ربطها من API أو ضمن مساحة التحقيق.','No resources linked yet. Resources can be linked through the API or investigation workspace.')}</div>}<h4>{words(en,'المهام','Tasks')}</h4>{(selected.tasks||[]).map((x:Row)=><div className="soc-task" key={x.id}><span>{x.title}</span><span className="status-chip muted-chip">{label(x.status,en)}</span></div>)}<h4>{words(en,'سجل القضية','Case timeline')}</h4>{(selected.timeline||[]).map((x:Row,i:number)=><div className="soc-timeline" key={`${x.resource_id}-${i}`}><i/><div><b>{x.label}</b><small>{fmt(x.at,en)}</small></div></div>)}<h4>{words(en,'ملاحظات','Notes')}</h4>{(selected.notes||[]).map((x:Row)=><div className="soc-note" key={x.id}>{x.note}<small>{fmt(x.created_at,en)}</small></div>)}<form className="soc-note-form" onSubmit={addNote}><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={words(en,'أضف ملاحظة للقضية','Add a case note')}/><button className="primary-btn compact" disabled={!note.trim()}><Plus size={14}/>{words(en,'إضافة ملاحظة','Add note')}</button></form></>:<div className="empty-state"><ClipboardIcon/><p>{words(en,'اختر قضية لعرض سجّلها وخطها الزمني.','Select a case to view its timeline and record.')}</p></div>}</section></div>
    {selected&&<form className="soc-inline-form case-link-form" onSubmit={linkResource}><select value={resourceType} onChange={e=>setResourceType(e.target.value)}>{['ALERT','EVENT','ASSET','FINDING','INCIDENT','INVESTIGATION','TASK','EVIDENCE'].map(x=><option key={x}>{x}</option>)}</select><input value={resourceId} onChange={e=>setResourceId(e.target.value)} placeholder={words(en,'معرّف المورد المراد ربطه','Resource ID to link')}/><button className="secondary-btn compact" disabled={!resourceId.trim()}><Plus size={14}/>{words(en,'ربط بالقضية','Link to case')}</button></form>}
  {selected&&<form className="soc-inline-form case-link-form" onSubmit={linkResource}><select value={resourceType} onChange={e=>setResourceType(e.target.value)}>{['ALERT','EVENT','ASSET','FINDING','INCIDENT','INVESTIGATION','TASK','EVIDENCE'].map(x=><option key={x}>{x}</option>)}</select><input value={resourceId} onChange={e=>setResourceId(e.target.value)} placeholder={words(en,'معرّف المورد المراد ربطه','Resource ID to link')}/><button className="secondary-btn compact" disabled={!resourceId.trim()}><Plus size={14}/>{words(en,'ربط بالقضية','Link to case')}</button></form>}
  </div>;
}
function ClipboardIcon(){return <Activity size={22}/>}

export function ThreatIntelPage({en,canManage=false}:Props & {canManage?:boolean}) {
  const [items,setItems]=useState<Row[]>([]),[kind,setKind]=useState('IP'),[value,setValue]=useState(''),[confidence,setConfidence]=useState('50'),[source,setSource]=useState('Organization'),[description,setDescription]=useState('');const {error,message,run}=useMessage();
  const load=useCallback(async()=>setItems(await api<Row[]>('/indicators')),[]);useEffect(()=>{void load().catch(()=>{})},[load]);
  async function create(e:FormEvent){e.preventDefault();await run(async()=>{await post('/indicators',{type:kind,value,confidence:Number(confidence),source,description,tags:[]});setValue('');setDescription('');await load()},words(en,'أُضيف المؤشر','Indicator added'))}
  return <div className="page-content"><Heading en={en} title={words(en,'استخبارات التهديدات','Threat intelligence')} description={words(en,'مؤشرات المؤسسة المطَبّعة محلياً؛ المطابقة إشارة تحليلية وليست حكماً قطعياً.','Organization-managed normalized indicators; a match is an analytical signal, not proof of maliciousness.')}/><Notice message={message} error={error} en={en}/><form className="soc-create-form" onSubmit={create}><div className="soc-form-row"><select value={kind} onChange={e=>setKind(e.target.value)}>{['IP','DOMAIN','URL','HASH','EMAIL'].map(x=><option key={x}>{x}</option>)}</select><input required value={value} onChange={e=>setValue(e.target.value)} placeholder={words(en,'قيمة المؤشر','Indicator value')}/><input type="number" min="0" max="100" value={confidence} onChange={e=>setConfidence(e.target.value)} aria-label="confidence"/><input value={source} onChange={e=>setSource(e.target.value)} placeholder={words(en,'المصدر','Source')}/></div><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder={words(en,'الوصف والسياق','Description and context')}/><button className="primary-btn"><Plus size={14}/>{words(en,'إضافة مؤشر','Add indicator')}</button></form><section className="table-card"><div className="section-head"><div><h3>{words(en,'قاعدة المؤشرات','Indicator database')}</h3><p>{items.length} {words(en,'مؤشراً','indicators')}</p></div><button className="secondary-btn compact" onClick={()=>void load()}><RefreshCw size={14}/></button></div><div className="soc-table-scroll"><table className="soc-table"><thead><tr><th>{words(en,'النوع','Type')}</th><th>{words(en,'القيمة','Value')}</th><th>{words(en,'الثقة','Confidence')}</th><th>{words(en,'المصدر','Source')}</th><th>{words(en,'آخر ظهور','Last seen')}</th><th/></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><span className="status-chip muted-chip">{x.type}</span></td><td className="indicator-value">{x.value}</td><td>{x.confidence}%</td><td>{x.source}</td><td>{fmt(x.last_seen,en)}</td><td>{canManage&&<button className="icon-danger" aria-label={words(en,'حذف','Delete')} onClick={async()=>{if(!confirm(words(en,'حذف هذا المؤشر؟','Delete this indicator?')))return;await run(()=>api(`/indicators/${x.id}`,{method:'DELETE'}),words(en,'تم حذف المؤشر','Indicator deleted'));await load()}}><Trash2 size={14}/></button>}</td></tr>)}</tbody></table>{!items.length&&<div className="empty-state"><Globe2/><p>{words(en,'لم تُسجّل مؤشرات بعد. لا يوجد مزوّد خارجي مفعل افتراضياً.','No indicators recorded. No external provider is enabled by default.')}</p></div>}</div></section></div>;
}

export function PlaybooksPage({en,canManage=false}:Props & {canManage?:boolean}) {
  const [items,setItems]=useState<Row[]>([]),[show,setShow]=useState(false),[name,setName]=useState(''),[trigger,setTrigger]=useState(''),[steps,setSteps]=useState('[{"type":"REQUEST_APPROVAL","label":"مراجعة المحلل","config":{}}]');const {error,message,run}=useMessage();
  const load=useCallback(async()=>setItems(await api<Row[]>('/playbooks')),[]);useEffect(()=>{void load().catch(()=>{})},[load]);
  async function create(e:FormEvent){e.preventDefault();let parsed;try{parsed=JSON.parse(steps);if(!Array.isArray(parsed))throw new Error()}catch{run(async()=>{throw new Error(words(en,'صيغة JSON للخطوات غير صحيحة','Steps must be valid JSON array'))});return}await run(async()=>{await post('/playbooks',{name,trigger,steps:parsed,enabled:true});setName('');setTrigger('');setShow(false);await load()},words(en,'أُنشئ الدليل','Playbook created'))}
  return <div className="page-content"><Heading en={en} title={words(en,'أدلة الاستجابة','Security playbooks')} description={words(en,'تعريف خطوات استجابة منظمة وآمنة؛ لا ينفّذ النظام أوامر عامة أو إجراءات خارجية تلقائياً.','Configure structured safe response steps. No arbitrary commands or external actions are run automatically.')} action={canManage?<button className="primary-btn" onClick={()=>setShow(!show)}><Plus size={15}/>{words(en,'دليل جديد','New playbook')}</button>:undefined}/><Notice message={message} error={error} en={en}/>{show&&canManage&&<form className="soc-create-form" onSubmit={create}><input required minLength={3} value={name} onChange={e=>setName(e.target.value)} placeholder={words(en,'اسم الدليل','Playbook name')}/><input required minLength={3} value={trigger} onChange={e=>setTrigger(e.target.value)} placeholder={words(en,'المحفز أو الوصف','Trigger or description')}/><label className="soc-label">{words(en,'خطوات منظمة (JSON)','Structured steps (JSON)')}<textarea className="code-textarea" value={steps} onChange={e=>setSteps(e.target.value)}/></label><small className="muted">CREATE_TASK · CREATE_INCIDENT · SET_ALERT_STATUS · REQUEST_APPROVAL · NOTIFY_WEBHOOK · GENERATE_REPORT</small><button className="primary-btn"><Check size={14}/>{words(en,'حفظ الدليل','Save playbook')}</button></form>}<div className="soc-card-grid">{items.map(x=><article className="soc-playbook" key={x.id}><div className="section-head"><span className="status-chip muted-chip">{x.enabled?words(en,'مفعّل','Enabled'):words(en,'متوقف','Disabled')}</span>{canManage&&<button className="secondary-btn compact" onClick={async()=>{await run(()=>patch(`/playbooks/${x.id}`,{enabled:!x.enabled}),words(en,'تم تحديث الحالة','Status updated'));await load()}}>{x.enabled?words(en,'إيقاف','Disable'):words(en,'تفعيل','Enable')}</button>}</div><h3>{x.name}</h3><p>{x.trigger}</p><ol>{(x.steps||[]).map((s:Row,i:number)=><li key={i}><b>{s.label||label(s.type,en)}</b><small>{label(s.type,en)}</small></li>)}</ol><small className="muted">{words(en,'التشغيل الآلي الكامل غير مفعّل.','Automated execution is not enabled.')}</small></article>)}{!items.length&&<div className="empty-state wide"><Activity/><p>{words(en,'لا توجد أدلة استجابة بعد.','No playbooks configured yet.')}</p></div>}</div></div>;
}

export function IntegrationsPage({en}:Props) {
  const [keys,setKeys]=useState<Row[]>([]),[hooks,setHooks]=useState<Row[]>([]),[keyName,setKeyName]=useState(''),[secret,setSecret]=useState(''),[hookUrl,setHookUrl]=useState(''),[hookSecret,setHookSecret]=useState(''),[hookEvents,setHookEvents]=useState<string[]>(['ALERT_CREATED','HIGH_SEVERITY_EVENT']),[createdKey,setCreatedKey]=useState('');const {error,message,run}=useMessage();
  const load=useCallback(async()=>{const [k,h]=await Promise.all([api<Row[]>('/api-keys'),api<Row[]>('/webhooks')]);setKeys(k);setHooks(h)},[]);useEffect(()=>{void load().catch(()=>{})},[load]);
  async function mint(e:FormEvent){e.preventDefault();await run(async()=>{const data=await post<Row>('/api-keys',{name:keyName,permissions:['EVENT_INGEST']});setCreatedKey(data.api_key);setKeyName('');await load()},words(en,'أُنشئ المفتاح؛ انسخه الآن، لن يظهر ثانية.','Key created. Copy it now; it will not be shown again.'))}
  async function createHook(e:FormEvent){e.preventDefault();await run(async()=>{await post('/webhooks',{url:hookUrl,secret:hookSecret,event_types:hookEvents});setHookUrl('');setHookSecret('');await load()},words(en,'تم حفظ الوجهة والسر المشفر؛ لن يعرض السر لاحقاً.','Endpoint saved with encrypted secret; it will not be shown again.'))}
  const toggle=(event:string)=>setHookEvents(prev=>prev.includes(event)?prev.filter(x=>x!==event):[...prev,event]);
  return <div className="page-content"><Heading en={en} title={words(en,'التكاملات ومفاتيح الإدخال','Integrations & ingestion keys')} description={words(en,'أنشئ مفاتيح أحداث محدودة وموقّعات Webhook اختيارية؛ القيم السرية تظهر مرة واحدة فقط.','Create scoped event-ingestion keys and optional signed webhooks. Secrets are shown only once.')}/><Notice message={message} error={error} en={en}/>{createdKey&&<div className="one-time-secret"><b>{words(en,'انسخ المفتاح الآن','Copy this key now')}</b><code>{createdKey}</code><button className="secondary-btn compact" onClick={()=>navigator.clipboard.writeText(createdKey)}>{words(en,'نسخ','Copy')}</button><button className="icon-danger" onClick={()=>setCreatedKey('')}><X size={14}/></button></div>}
    <div className="soc-two-col"><section className="table-card"><div className="section-head"><div><h3>{words(en,'مفاتيح API لإدخال الأحداث','Event ingestion API keys')}</h3><p>{words(en,'Bearer keys، مخزنة كبصمة وقابلة للإبطال.','Bearer keys stored as hashes and revocable.')}</p></div><KeyRound size={18}/></div><form className="soc-inline-form" onSubmit={mint}><input required minLength={2} value={keyName} onChange={e=>setKeyName(e.target.value)} placeholder={words(en,'اسم المصدر (مثلاً Web server)','Source name (e.g. web server)')}/><button className="primary-btn compact"><Plus size={14}/>{words(en,'إنشاء مفتاح','Create key')}</button></form>{keys.map(x=><div className="soc-integration-row" key={x.id}><KeyRound size={15}/><span><b>{x.name}</b><small>{x.key_prefix}… · {x.permissions?.join(', ')} · {x.per_minute_limit}/min</small></span>{x.revoked_at?<span className="status-chip danger">{words(en,'مبطل','Revoked')}</span>:<button className="icon-danger" title={words(en,'إبطال المفتاح','Revoke key')} onClick={async()=>{if(!confirm(words(en,'إبطال هذا المفتاح؟ سيتوقف مصدره عن الإدخال.','Revoke this key? Its source will stop ingesting.')))return;await run(()=>api(`/api-keys/${x.id}`,{method:'DELETE'}),words(en,'تم إبطال المفتاح','Key revoked'));await load()}}><Trash2 size={14}/></button>}</div>)}</section>
    <section className="table-card"><div className="section-head"><div><h3>{words(en,'Webhook صادر','Outbound webhooks')}</h3><p>{words(en,'توقيع HMAC، نطاق أحداث مختار، وحماية SSRF.','HMAC signed, event-scoped, SSRF-protected.')}</p></div><Globe2 size={18}/></div><form className="soc-create-form compact-form" onSubmit={createHook}><input type="url" required value={hookUrl} onChange={e=>setHookUrl(e.target.value)} placeholder="https://receiver.example.com/events"/><input minLength={32} required value={hookSecret} onChange={e=>setHookSecret(e.target.value)} placeholder={words(en,'سر HMAC (32 حرفاً على الأقل)','HMAC secret (32+ characters)')}/><div className="soc-checks">{['ALERT_CREATED','INCIDENT_CREATED','SCAN_COMPLETED','HIGH_SEVERITY_EVENT'].map(x=><label key={x}><input type="checkbox" checked={hookEvents.includes(x)} onChange={()=>toggle(x)}/>{x}</label>)}</div><button className="primary-btn compact" disabled={!hookEvents.length}><Plus size={14}/>{words(en,'إضافة وجهة','Add endpoint')}</button></form>{hooks.map(x=><div className="soc-integration-row" key={x.id}><Globe2 size={15}/><span><b>{new URL(x.url).hostname}</b><small>{x.event_types?.join(', ')}</small></span><button className="icon-danger" onClick={async()=>{if(!confirm(words(en,'تعطيل هذه الوجهة؟','Disable this endpoint?')))return;await run(()=>api(`/webhooks/${x.id}`,{method:'DELETE'}),words(en,'تم تعطيل الوجهة','Endpoint disabled'));await load()}}><X size={14}/></button></div>)}</section></div>
    <div className="table-card soc-ingest-doc"><h3>{words(en,'عقد إدخال الحدث','Event ingestion contract')}</h3><p><code>POST /api/events/ingest</code> مع ترويسة <code>Authorization: Bearer &lt;organization-key&gt;</code>. لا ترسل <code>organization_id</code>؛ يؤخذ نطاق المؤسسة من المفتاح. لا تسجّل المفتاح في Git أو المتصفح، ودوّره فور الاشتباه بتسربه.</p><pre>{'{ "source": "web-gateway", "source_type": "WEB_SERVER", "event_type": "ACCESS_DENIED", "severity": "MEDIUM", "hostname": "edge.example.com", "message": "Request denied", "metadata": {} }'}</pre></div>
  </div>;
}

export function ApprovalsPage({en,canManage=false}:Props & {canManage?:boolean}) {
  const [items,setItems]=useState<Row[]>([]),[note,setNote]=useState(''),[actionType,setActionType]=useState('CONTAINMENT_REVIEW'),[payload,setPayload]=useState('{"scope":"single account"}');const {error,message,run}=useMessage();const load=useCallback(async()=>{if(canManage)setItems(await api<Row[]>('/approvals'))},[canManage]);useEffect(()=>{void load().catch(()=>{})},[load]);
  async function decide(row:Row,status:string){const text=note;await run(()=>post(`/approvals/${row.id}/decision`,{status,note:text}),status==='APPROVED'?words(en,'تمت الموافقة وتنفيذ الإجراء الداخلي المسموح.','Approved; supported internal action executed.'):words(en,'تم رفض الطلب.','Request rejected.'));setNote('');await load()}
  async function requestApproval(e:FormEvent){e.preventDefault();let parsed;try{parsed=JSON.parse(payload);if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw new Error()}catch{await run(async()=>{throw new Error(words(en,'حمولة JSON غير صحيحة.','Invalid JSON payload.'))});return}await run(async()=>{await post('/approvals',{action_type:actionType,action_payload:parsed});await load()},words(en,'أُرسل الطلب للمراجعة','Request submitted for review'))}
  return <div className="page-content"><Heading en={en} title={words(en,'طلبات الموافقة','Approval queue')} description={words(en,'يُنفّذ الإجراء الداخلي المدعوم فقط بعد موافقة مدير مختلف عن الطالب. لا تُنفذ أوامر خارجية.','Only supported internal actions execute after approval by a different manager. No external commands run.')}/><Notice message={message} error={error} en={en}/><form className="soc-create-form" onSubmit={requestApproval}><div className="soc-form-row"><select value={actionType} onChange={e=>setActionType(e.target.value)}>{['CONTAINMENT_REVIEW','CREATE_TASK','SET_ALERT_STATUS','CREATE_INCIDENT'].map(x=><option key={x}>{x}</option>)}</select><button className="primary-btn"><Plus size={14}/>{words(en,'طلب موافقة','Request approval')}</button></div><label className="soc-label">{words(en,'تفاصيل الإجراء (JSON)','Action details (JSON)')}<textarea className="code-textarea" value={payload} onChange={e=>setPayload(e.target.value)}/></label><small className="muted">{words(en,'تُراجع الحمولات ثم تتحقق الخوادم من صلاحيتها والنطاق المؤسسي. الإجراءات الخارجية غير مدعومة.','Payloads are validated server-side and scoped to the organization. External actions are not supported.')}</small></form>{canManage&&<section className="table-card"><div className="section-head"><h3>{words(en,'الطلبات المسجلة','Recorded requests')}</h3><button className="secondary-btn compact" onClick={()=>void load()}><RefreshCw size={14}/></button></div><div className="soc-list">{items.map(row=><article className="soc-approval" key={row.id}><div><b>{row.action_type}</b><span className={`status-chip ${row.status==='PENDING'?'warn':'muted-chip'}`}>{row.status}</span><pre>{JSON.stringify(row.action_payload,null,2)}</pre><small>{words(en,'الطالب','Requested by')}: {row.requested_by_id} · {fmt(row.created_at,en)}</small>{row.execution_result&&<small>{words(en,'النتيجة','Result')}: {JSON.stringify(row.execution_result)}</small>}</div>{row.status==='PENDING'&&<div className="soc-approval-actions"><input value={note} onChange={e=>setNote(e.target.value)} placeholder={words(en,'ملاحظة القرار','Decision note')}/><button className="primary-btn compact" onClick={()=>void decide(row,'APPROVED')}><Check size={14}/>{words(en,'موافقة','Approve')}</button><button className="secondary-btn compact" onClick={()=>void decide(row,'REJECTED')}><X size={14}/>{words(en,'رفض','Reject')}</button></div>}</article>)}{!items.length&&<div className="empty-state"><Check/><p>{words(en,'لا توجد طلبات معلقة.','No approval requests.')}</p></div>}</div></section>}</div>;
}
